apiVersion: networking.k8s.io
kind: Ingress
metadata:
  name: ingress-myservicea
spec:
  ingressClassName: nginx
  rules:
  - host: ticketing.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backend-srv
            port:
              number: 80
